server:
  port: 7001
  servlet:
    context-path: /ad-search

spring:
  application:
    name: eureka-client-ad-search
  datasource:
    url: jdbc:mysql://localhost:3306/ad-data?serverTimezone=GMT%2B8
    username: root
    password: 123456
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: ture
    open-in-view: false
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    listener:
      concurrency: 4

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

# 使用feign访问其他微服务
feign:
  hystrix:
    enabled: true

# 服务的监控 暴露所有
management:
  endpoints:
    web:
      exposure:
        include: "*"

# 73
adconf:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: 123456
    binlogName: ""
    position: -1

    kafka:
      topic: ad-search-mysql-data