server:
  port: 7001

spring:
  application:
    name: eureka-client-ad-sponsor
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/ad_data
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false

eureka:
  client:
    service-url:
     defaultZone: http://localhost:8000/eureka/
